; Rotatron SNES - ROM data (header + converted graphics).
.include "hdr.asm"

; ---- Board BG1 tileset (4bpp, generated by tools/build_board_gfx.py) ----
.section ".rodata_board" superfree
board_pic: .incbin "res/board.pic"
board_picend:
board_pal: .incbin "res/board.pal"
.ends

; ---- Cursor OBJ sprite (16x16 ring, 4 tiles TL/TR/BL/BR) ----
.section ".rodata_cursor" superfree
cursor_pic: .incbin "res/cursor.pic"
cursor_picend:
cursor_pal: .incbin "res/cursor.pal"
.ends
