; Rotatron SNES - ROM data (header + converted graphics).
.include "hdr.asm"

; ---- Board BG1 tileset (4bpp, generated by tools/build_board_gfx.py) ----
.section ".rodata_board" superfree
board_pic: .incbin "res/board.pic"
board_picend:
board_pal: .incbin "res/board.pal"
.ends

; ---- Spin animation OBJ frames (6x 64x64, sector-indexed palette) ----
.section ".rodata_spin" superfree
spin_pic: .incbin "res/spin.pic"
.ends

; ---- Cursor OBJ sprite (16x16 ring, 4 tiles TL/TR/BL/BR) ----
.section ".rodata_cursor" superfree
cursor_pic: .incbin "res/cursor.pic"
cursor_picend:
cursor_pal: .incbin "res/cursor.pal"
.ends

; ---- Hex-clear pulse rings (4 frames 32x32, rows-26..29 band layout) ----
.section ".rodata_pulse" superfree
pulse_pic: .incbin "res/pulse.pic"
.ends

; ---- Seam spark OBJ frames (2x 16x16, bright + dim) ----
.section ".rodata_spark" superfree
spark_pic: .incbin "res/spark.pic"
.ends

; ---- HUD font (deadfall hud_font2t: 2bpp, ASCII 32-95, transparent bg) ----
.section ".rodata_hudfont" superfree
hudfont_pic: .incbin "res/hudfont.pic"
.ends

; ---- Ambient sky sprites (ship + shooting star, 16x16 each) ----
.section ".rodata_ambient" superfree
ambient_pic: .incbin "res/ambient.pic"
.ends

; ---- Mode-3 title screen (backdrops/title.png, 8bpp; pic split so each
; ---- section fits a 32KB bank) + studio logo for the boot drop ----
.section ".rodata_title8a" superfree
title8a_pic: .incbin "res/title8a.pic"
title8a_picend:
.ends
.section ".rodata_title8b" superfree
title8b_pic: .incbin "res/title8b.pic"
title8b_picend:
title8_map: .incbin "res/title8.map"
title8_pal: .incbin "res/title8.pal"
.ends
.section ".rodata_logo8" superfree
logo8_pic: .incbin "res/logo8.pic"
logo8_picend:
logo8_map: .incbin "res/logo8.map"
logo8_pal: .incbin "res/logo8.pal"
.ends

; ---- Per-phase BG2 backdrops (backdrops/level1-4.png). Each pic nearly
; fills a 32KB LoROM bank -> own section; maps+pals share one section. ----
.section ".rodata_bgl1pic" superfree
bgl1_pic: .incbin "res/bgl1.pic"
bgl1_picend:
.ends
.section ".rodata_bgl2pic" superfree
bgl2_pic: .incbin "res/bgl2.pic"
bgl2_picend:
.ends
.section ".rodata_bgl3pic" superfree
bgl3_pic: .incbin "res/bgl3.pic"
bgl3_picend:
.ends
.section ".rodata_bgl4pic" superfree
bgl4_pic: .incbin "res/bgl4.pic"
bgl4_picend:
.ends
.section ".rodata_bglmaps" superfree
bgl1_map: .incbin "res/bgl1.map"
bgl1_pal: .incbin "res/bgl1.pal"
bgl2_map: .incbin "res/bgl2.map"
bgl2_pal: .incbin "res/bgl2.pal"
bgl3_map: .incbin "res/bgl3.map"
bgl3_pal: .incbin "res/bgl3.pal"
bgl4_map: .incbin "res/bgl4.map"
bgl4_pal: .incbin "res/bgl4.pal"
.ends
