; Rotatron SNES - ROM data (header + converted graphics).
.include "hdr.asm"

; ---- Board BG1 tileset (4bpp, generated by tools/build_board_gfx.py) ----
.section ".rodata_board" superfree
board_pic: .incbin "res/board.pic"
board_picend:
board_pal: .incbin "res/board.pal"
.ends

; ---- Spin animation OBJ frames (6x 64x64, sector-indexed palette) ----
.section ".rodata_spin" superfree
spin_pic: .incbin "res/spin.pic"
.ends

; ---- Cursor OBJ sprite (16x16 ring, 4 tiles TL/TR/BL/BR) ----
.section ".rodata_cursor" superfree
cursor_pic: .incbin "res/cursor.pic"
cursor_picend:
cursor_pal: .incbin "res/cursor.pal"
.ends

; ---- Hex-clear pulse rings (4 frames 32x32, rows-26..29 band layout) ----
.section ".rodata_pulse" superfree
pulse_pic: .incbin "res/pulse.pic"
.ends

; ---- Seam spark OBJ frames (2x 16x16, bright + dim) ----
.section ".rodata_spark" superfree
spark_pic: .incbin "res/spark.pic"
.ends

; ---- HUD font (deadfall hud_font2t: 2bpp, ASCII 32-95, transparent bg) ----
.section ".rodata_hudfont" superfree
hudfont_pic: .incbin "res/hudfont.pic"
.ends

; ---- Ambient sky sprites (ship + shooting star, 16x16 each) ----
.section ".rodata_ambient" superfree
ambient_pic: .incbin "res/ambient.pic"
.ends

; ---- BG2 backdrop (quantized backdrops/level1.png) ----
; The pic alone nearly fills a 32KB LoROM bank, so it gets its own
; superfree section; map+pal live separately (deadfall bgtex pattern).
.section ".rodata_bg2pic" superfree
bg2_pic: .incbin "res/bg2.pic"
bg2_picend:
.ends
.section ".rodata_bg2map" superfree
bg2_map: .incbin "res/bg2.map"
bg2_pal: .incbin "res/bg2.pal"
.ends
