#ifndef AMBTAB_H
#define AMBTAB_H
/* GENERATED by tools/build_board_gfx.py - do not edit. Ambient flyer table. */
#define AMB_SPRITE_N 9
#define AMB_TILE_BYTES 1280
#define AMB_PAL_OFF (AMB_SPRITE_N * AMB_TILE_BYTES)
#define AMB_PAL_BYTES 22
#define AMB_DOT_OFF (AMB_PAL_OFF + AMB_SPRITE_N * AMB_PAL_BYTES)
#define AMB_PICK_MASK 15  /* smallest 2^k-1 >= N-1, for rejection sampling */
static const u8 ambSpriteCols[AMB_SPRITE_N] = {5, 3, 4, 5, 5, 5, 5, 5, 5};
static const u8 ambSpriteMotion[AMB_SPRITE_N] = {0, 1, 0, 0, 0, 0, 0, 0, 0}; /* 0=H, 1=D */
#endif
