/* Generated by tools/build_audio.py - SFX indices in res/sfx.it */
#ifndef AUDIO_SFX_H
#define AUDIO_SFX_H

#define SFX_TURNWHEEL  0
#define SFX_HEXAGON    1
#define SFX_HEXAGONNEW 2
#define SFX_EXTRABONUS 3
#define SFX_COLORELIM  4
#define SFX_LEVELUP    5
#define SFX_GAMEOVER   6
#define SFX_LOGOTHUD   7

#define SFX_COUNT 8

#endif
