/* GENERATED by tools/build_backdrop.py - do not edit. */
#ifndef BG2TAB_H
#define BG2TAB_H
#include "core_types.h"
#define TWINKLE_N 3
static const u8 twSlot[TWINKLE_N] = {1, 2, 4};
static const u16 twColor[TWINKLE_N] = {22986, 15653, 13540};
#endif
