/* GENERATED by tools/build_board_gfx.py - do not edit. */
#ifndef BOARDTAB_H
#define BOARDTAB_H
#include "core_types.h"

#define BOARD_TILES_W 24
#define BOARD_TILES_H 21
#define N_STRUCTS 26
#define N_BOARD_VRAM_TILES 103
#define N_TRIANGLES 54

extern const u8 cellStruct[BOARD_TILES_H][BOARD_TILES_W];   /* 0xFF = blank */
extern const u8 cellTriA[BOARD_TILES_H][BOARD_TILES_W];
extern const u8 cellTriB[BOARD_TILES_H][BOARD_TILES_W];     /* 0xFF = single owner */
extern const u8 structOwners[N_STRUCTS];                    /* 1 or 2 */
extern const u16 structBase[N_STRUCTS];
extern const u16 entryTable[396];            /* tile | flip bits */
extern const u8 triCol[N_TRIANGLES];
extern const u8 triRow[N_TRIANGLES];
extern const u8 triOfCell[7][12];                  /* 0xFF outside hex */
extern const u16 triCellOfs[N_TRIANGLES + 1];
extern const u8 triCellXY[1080];              /* tx,ty pairs */
#endif
