/* AUTO-GENERATED by tools/gen_soundbank_banks.py from soundbank.asm.
 * Do not edit. Lists the 3 ROM bank(s) the soundbank spans. */
#ifndef SOUNDBANK_BANKS_H
#define SOUNDBANK_BANKS_H
extern char SOUNDBANK__0, SOUNDBANK__1, SOUNDBANK__2;
/* register highest bank first (per PVSnesLib musicGreaterThan32k) */
#define SPC_SET_ALL_BANKS() do { \
    spcSetBank(&SOUNDBANK__2); \
    spcSetBank(&SOUNDBANK__1); \
    spcSetBank(&SOUNDBANK__0); \
} while (0)
#endif
