/* AUTO-GENERATED by tools/gen_soundbank_banks.py from soundbank.asm.
 * Do not edit. Lists the 1 ROM bank(s) the soundbank spans. */
#ifndef SOUNDBANK_BANKS_H
#define SOUNDBANK_BANKS_H
extern char SOUNDBANK__;
/* register highest bank first (per PVSnesLib musicGreaterThan32k) */
#define SPC_SET_ALL_BANKS() do { \
    spcSetBank(&SOUNDBANK__); \
} while (0)
#endif
