#!/usr/bin/env python3
"""Build the Rotatron SFX soundbank module (res/sfx.it) from music/s-*.mp3.

Each web-game sound effect -> mono 8kHz, trimmed, normalized -> one IT
sample; spcLoadEffect/spcEffect address them by index (audio_sfx.h, emitted
here). ARAM is 64KB shared with the snesmod driver and the ~28KB music
module, so every resident effect stays <=0.6s (deadfall learned that longer
resident effects corrupt the boot-time effect load). The long game-over
sting is therefore truncated; promote it to a tiny music-module stinger if
the cut feels wrong.
"""
import os
import subprocess
import numpy as np
from make_it import write_it

HERE = os.path.dirname(__file__)
SRC = os.path.join(HERE, "..", "music")
RES = os.path.join(HERE, "..", "res")
INC = os.path.join(HERE, "..", "include")

RATE = 8000   # played at spcEffect pitch=2 (=8kHz) for natural rate
MAXLEN = 0.6

# (C name, source file[, max seconds]). Order defines the effect index.
SFX = [
    ("TURNWHEEL", "s-turnwheel"),
    ("HEXAGON", "s-hexagon"),
    ("HEXAGONNEW", "s-hexagonnew"),
    ("EXTRABONUS", "s-extrabonus"),
    ("COLORELIM", "s-coloreliminated"),
    ("LEVELUP", "s-levelup"),
    ("GAMEOVER", "s-gameover"),
    ("LOGOTHUD", "s-logothud"),
]


def decode(name, maxlen=MAXLEN):
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", f"{SRC}/{name}.mp3",
         "-ac", "1", "-ar", str(RATE), "-f", "s16le", "-"],
        capture_output=True, check=True).stdout
    pcm = np.frombuffer(raw, dtype="<i2").astype(np.float32)
    if len(pcm) == 0:
        return np.zeros(16, np.int16)
    thr = max(200.0, np.abs(pcm).max() * 0.02)
    nz = np.where(np.abs(pcm) > thr)[0]
    if len(nz):
        pcm = pcm[: min(len(pcm), nz[-1] + RATE // 50)]
    pcm = pcm[: int(maxlen * RATE)]
    peak = np.abs(pcm).max()
    if peak > 0:
        pcm = pcm * (28000.0 / peak)
    pad = (-len(pcm)) % 16
    if pad:
        pcm = np.concatenate([pcm, np.zeros(pad, np.float32)])
    return np.clip(pcm, -32768, 32767).astype(np.int16)


def main():
    samples = []
    total = 0
    for entry in SFX:
        cname, fname = entry[0], entry[1]
        mlen = entry[2] if len(entry) > 2 else MAXLEN
        pcm = decode(fname, mlen)
        total += len(pcm)
        samples.append({"name": cname, "pcm": pcm, "rate": RATE, "loop": None})
        print(f"  {cname:10s} {len(pcm):6d} samples ({len(pcm) / RATE:.2f}s)")
    out = os.path.join(RES, "sfx.it")
    n = write_it(out, "ROTATRON SFX", samples, channels=8)
    print(f"wrote {out}: {n} bytes, {len(samples)} SFX, "
          f"~{total * 9 // 16 / 1024:.1f}KB BRR (ARAM)")

    with open(os.path.join(INC, "audio_sfx.h"), "w") as f:
        f.write("/* Generated by tools/build_audio.py - SFX indices in res/sfx.it */\n")
        f.write("#ifndef AUDIO_SFX_H\n#define AUDIO_SFX_H\n\n")
        for i, entry in enumerate(SFX):
            f.write(f"#define SFX_{entry[0]:10s} {i}\n")
        f.write(f"\n#define SFX_COUNT {len(SFX)}\n")
        f.write("\n#endif\n")
    print(f"wrote include/audio_sfx.h ({len(SFX)} indices)")


if __name__ == "__main__":
    main()
