#!/usr/bin/env python3
"""Generate include/soundbank_banks.h from res/soundbank.asm.

The snesmod soundbank spans N 32KB ROM banks (symbols SOUNDBANK__0..__{N-1}); the
count depends on the combined module sizes and smconv's bank packing, so it
changes whenever the music set changes. audio.c must register EXACTLY those banks
with spcSetBank: reference one that doesn't exist -> link error ("Unresolved
SOUNDBANK__n"); fail to reference one that does -> the linker discards it and any
module living there is silent. Generating the list each build keeps them in sync.

Usage: gen_soundbank_banks.py <soundbank.asm> <out.h>   (run from the Makefile)
"""
import re
import sys

asm, out = sys.argv[1], sys.argv[2]
# Parse the ACTUAL labels: a multi-bank soundbank emits SOUNDBANK__0..N-1,
# but a single-bank one emits plain "SOUNDBANK__" (no suffix).
text = open(asm).read()
labels = re.findall(r'^(SOUNDBANK__\d*):', text, re.M)
if not labels:
    sys.exit("gen_soundbank_banks: no SOUNDBANK__ labels in %s" % asm)
labels.sort(key=lambda s: int(s[11:]) if len(s) > 11 else 0)
n = len(labels)

lines = [
    "/* AUTO-GENERATED by tools/gen_soundbank_banks.py from soundbank.asm.",
    " * Do not edit. Lists the %d ROM bank(s) the soundbank spans. */" % n,
    "#ifndef SOUNDBANK_BANKS_H",
    "#define SOUNDBANK_BANKS_H",
    "extern char " + ", ".join(labels) + ";",
    "/* register highest bank first (per PVSnesLib musicGreaterThan32k) */",
    "#define SPC_SET_ALL_BANKS() do { \\",
]
lines += ["    spcSetBank(&%s); \\" % lbl for lbl in reversed(labels)]
lines += ["} while (0)", "#endif", ""]

with open(out, "w") as f:
    f.write("\n".join(lines))
print("gen_soundbank_banks: %d bank(s) -> %s" % (n, out))
